---
title: "PRISMA flowcharts"
output: github_document
always_allow_html: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE) #defines default echo (display code)
knitr::opts_chunk$set(eval = TRUE) #defines default eval (display result of code)
knitr::opts_chunk$set(comment = "") # no space/character before results (e.g. in tables)
knitr::opts_chunk$set(tidy = T) # let r reformat your code to look tidy in the output
knitr::opts_chunk$set(collapse = F) # should code and results be shown in the same chunk (=T) or be split in several chunks in the document (=F)
```

Start by loading the library.

```{r libraries}
library(PRISMAstatement)
```

Next, make an exclusion flowchart for the base clinical model with overall survival as outcome:

```{r base clinical OS}
dot <- 
  flow_exclusions_dot(
    incl_counts = c(972, 132, 77, 14),
    total_label = "Total Screened",
    incl_labels = c("Consented", "Completed Study", "BMI 30"),
    excl_labels = c("Declined Consent", "Failed to Complete", "BMI 30"),
    percent_of_total = TRUE
    )
DiagrammeR::grViz(dot) 

```

